productly/productly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("productos/", include("productos.urls")),
]

productly/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"
urlpatterns = [
    path("", views.index, name="index"),
    path("formulario", views.formulario, name="formulario"),
    path("<int:producto_id>", views.detalle, name="detalle"),
]

productly/productos/models.py
"""Module providing a function printing python version."""

from django.db import models
from django.utils import timezone


# Create your models here.
class Categoria(models.Model):
    """Class representing a categoria"""

    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    """Class representing a producto"""

    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    creado_en = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

productly/productos/forms.py
from . import models
from django.forms import ModelForm


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ["nombre", "stock", "puntaje", "categoria"]

productly/productos/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ProductoForm
from .models import Producto


# Create your views here.
def index(request):
    productos = Producto.objects.all()

    return render(request, "index.html", context={"productos": productos})


def detalle(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    return render(request, "detalle.html", context={"producto": producto})


def formulario(request):

    if request.method == "POST":
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/productos")
    else:
        form = ProductoForm()
    return render(request, "producto_form.html", {"form": form})

productly/productos/templates/detalle.html
{%extends 'base.html'%}

{%block content%}
<div>
    <h6>{{producto.nombre}}</h6>
    <p>{{producto.categoria}}</p>
    <p>{{producto.stock}}</p>
    <p> {{producto.puntaje}}</p>
    <p> {{producto.creado_en}}</p>
</div>
{%endblock%}

productly/productos/templates/index.html
{% extends 'base.html' %}

{% block content %}



<h1>Productos</h1>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoria</th>
        </tr>
    </thead>

    <tbody>
        {% for producto in productos %}
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    {{producto.nombre}}
                </a>
            </td>
            <td>{{producto.stock}}</td>
            <td>{{producto.puntaje}}</td>
            <td>{{producto.categoria}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
{% endblock %}

productly/productos/templates/producto_form.html
{% extends 'base.html' %}


{% block content  %}
<form 
    novalidate
    action = "{% url 'productos:formulario' %}" 
    method='post'>
    {% csrf_token %}
    {{ form }}
</br>
    <input type="submit" value="Enviar" />
</form>    
{% endblock  %}



productly/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

productly/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

productly/templates/django/forms/widgets/input.html
<input 
class="form-control" {{widget.attrs.class}}
type="{{ widget.type }}" 
name="{{ widget.name }}"{% if widget.value != None %} 
value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}>

productly/templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>

productly/templates/form_snippet.html
{% load add_attr%}
{% for field in form  %}
<div class="mb-3">
    {{ field.label_tag }} 

    {% if field.errors %}
        {{ field|add_attr:"class:is-invalid" }}
    {% else %}
        {{ field }}
    {% endif %}
    <div class="invalid-feedback">
    {% for error in field.errors %}
        {{ error }}
    {% endfor %}
    </div>
</div>        
{% endfor %}